import Sidebar from "@/components/sidebar/Sidebar";
import "./styles/globals.css";

export const metadata = {
  title: "Nominapp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Sidebar />
        <main id="main-content">{children}</main>
      </body>
    </html>
  );
}
